version: '3.9'

services:
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: contract_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root123
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    server:
        build: ./server
        environment:
            PORT: 3000
            PREFIX: /api
            CLIENT_URL: http://localhost:5173
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: root123
            DB_NAME: contract_db
        depends_on:
            - db
        ports:
            - '3000:3000'

    client:
        build: ./client
        depends_on:
            - server
        ports:
            - '5173:80'

volumes:
    mysql_data:
