version: '3.9'

services:
    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: contract_db
            MYSQL_USER: root
            MYSQL_PASSWORD: root123
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    # nest-app:
    #     build: .
    #     container_name: nest_backend
    #     ports:
    #         - '3000:3000'
    #     depends_on:
    #         - mysql
    #     environment:
    #         DATABASE_URL: mysql://root:root123@mysql:3306/contract_db
    #     command: sh -c "npx prisma generate && npm run start:prod"

volumes:
    mysql_data:
